### ISSUE TITLE
Pricing error leads to funny values 

### ISSUE THREAD

**Issue by Noctis-** [Qt-dev/exile-diary#246] opened 2023-12-05 21:49 UTC
I mean, i wish i could say i was that good, but ... no ... this feels wrong :)
1.4.3. I think i've tried changing from normal to alternate splinter pricing, but i don't know if that takes effect only for the next map run or not (done it after i've seen the weird numbers)

![image](https://github.com/Qt-dev/exile-diary/assets/6160139/d79640d1-8983-4ff0-9845-22fa803db7db)

![image](https://github.com/Qt-dev/exile-diary/assets/6160139/b4f01ee1-6c17-4cb2-9bf7-c6f5cf32cb9e)

![image](https://github.com/Qt-dev/exile-diary/assets/6160139/c0568b66-2e68-4ed2-b7f6-2ec1d6c95fed)

**Comment by Qt-dev** [comment] 2023-12-05 22:48
Lol yeah I saw that. Cant do much about it.
The issue is that there is not enough trading so poe.ninja prices get all weird.

This time:
![image0](https://github.com/Qt-dev/exile-diary/assets/3586102/c606d09e-cb1e-4f21-af0a-edbcae54e9f6)


I cannot do much about that right now. Maybe I can look into pricing stuff using poestack or something, but that's for the future hehe

**Comment by Qt-dev** [comment] 2023-12-06 18:27
When you switch pricing between alternate and not alternate, it will change any FUTURE pricing.
You can trigger re-pricing of all stuff for the day, or even previous days, from the Debug tab in the settings though.

**Comment by Qt-dev** [comment] 2023-12-08 18:43
Closing this for cleanup :)

**Closed by Qt-dev** 2023-12-08 18:43 UTC
