### ISSUE TITLE
Exit Vaal area causes error

### ISSUE THREAD

**Issue by mSoul01** [Qt-dev/exile-diary#64] opened 2023-05-01 16:09 UTC
Error:
```AxiosError: Request failed with status code 429
    at settle (C:\Users\Geras\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\node_modules\axios\dist\node\axios.cjs:1909:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Geras\AppData\Local\Programs\Exile Diary Reborn\resources\app.asar\node_modules\axios\dist\node\axios.cjs:2989:11)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```
OS: Windows NT 10.0.22621

[change_areas.txt](https://github.com/Qt-dev/exile-diary/files/11366517/change_areas.txt)

**Comment by Qt-dev** [comment] 2023-05-02 02:00
This is apparently a duplicate of #62. The error is still that "too many request" part, it just happened when it looked for your latest inventory, which is any time you enter a zone. I do not see any trace of it being Vaal or anything else. I'll close this for now and concentrate on checking the other :)

**Closed by Qt-dev** 2023-05-02 02:00 UTC
